platform :ios, 8.0

inhibit_all_warnings!

project 'TestFavorites.xcodeproj'

pod 'Masonry'
pod 'NSData+Base64'
pod 'AFNetworking'
pod 'ReactiveCocoa' , '2.1.3'
pod 'Mantle'
pod 'ReactiveViewModel'
pod 'ObjectiveSugar', :git => 'https://github.com/SergeyBulyno/ObjectiveSugar.git'

target 'TestFavorites'